import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react';
import styles from '../styles/Home.module.css'
import NewsSection from '../components/NewsSection';
import Footer from '../components/Footer';

export default function Home() {
  
  const category=null;
  const [page,setPage]=useState(1);
  
  const API=`https://newsapi.org/v2/top-headlines?country=us&page=${page}&pageSize=12${category!==null ? `&category=`+category:''}&apiKey=61403e63fb404f399b00c46d03231b62`

  return (
    <>
      <Head>
        <title>Home - dr.news</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"></meta>
      </Head>

      <NewsSection API={API} setPage={setPage} page={page}/>
      
      <Footer selected={'home'}/>
    </>
  )
}
