import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react';
import styles from '../styles/Home.module.css'
import NewsSection from '../components/NewsSection';
import Footer from '../components/Footer';

export default function Home() {
  
  const category=null;
  const [page,setPage]=useState(0);
  
  
  const KEY = 'djQ8gPEHON5Pnk7jTNhTelR8M8Bg5Pmd'
  const API=`https://api.nytimes.com/svc/news/v3/content/nyt/all.json?limit=12&offset=${page}&api-key=${KEY}`;
  

  return (
    <>
      <Head>
        <title>Home - dr.news</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"></meta>
      </Head>

      <NewsSection API={API} setPage={setPage} page={page}/>
      
      <Footer selected={'home'}/>
    </>
  )
}
