import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react';
import styles from '../styles/Home.module.css'
import NewsSection from '../components/NewsSection';
import Footer from '../components/Footer';

export default function Home() {


  const Art=`https://www.nytimes.com/2022/07/20/briefing/europe-heatwave-global-warming-climate.html&api-key=${KEY}`;
  
  function newArticles(API) {
    fetch(API)
    .then(res=>res.json())
    .then(res=>console.log(res))
  }

  useEffect(()=>{
    newArticles(API)
  },[])

  return (
    <>
      <Head>
        <title>Home - dr.news</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"></meta>
      </Head>
      <main>
        <h1>Main</h1>
      </main>
      
      <Footer selected={'home'}/>
    </>
  )
}
