import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react';
import styles from '../styles/Home.module.css'
import SearchSection from '../components/SearchSection';
import Footer from '../components/Footer';
import QForm from '../components/QForm';
import {AiOutlineSearch} from 'react-icons/ai'


export default function Search() {
  
  const category=null;
  const [page,setPage]=useState(0);



  const [q,setQ]=useState('')

  const KEY = 'djQ8gPEHON5Pnk7jTNhTelR8M8Bg5Pmd'
  const API=`https://api.nytimes.com/svc/search/v2/articlesearch.json?q=${q}&page=${page}&sort=newest&api-key=${KEY}`
  
  return (
    <div className='angel'>
      <Head>
        <title>{q==='' ? 'Search' : q} - dr.news</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"></meta>
      </Head>

        {q==='' 
            ?
                <QForm q={q} setQ={setQ}/>
            :
                <>
                  <SearchSection API={API} setPage={setPage} page={page} q={q} setQ={setQ}/>
                  <AiOutlineSearch onClick={()=>{setQ('')}} id='search-icon'/>
                </>
        }


      <Footer selected={'search'}/>

    </div>
  )
}
