import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react';
import styles from '../styles/Home.module.css'
import NewsSection from '../components/NewsSection';
import Footer from '../components/Footer';
import QForm from '../components/QForm';

export default function Search() {
  
  const category=null;
  const [page,setPage]=useState(1);

  const [q,setQ]=useState('')
  
  const API=`https://newsapi.org/v2/everything?q=${q}&language=en&sortBy=publishedAt&page=${page}&pageSize=10&apiKey=61403e63fb404f399b00c46d03231b62`
  return (
    <>
      <Head>
        <title>{q==='' ? 'Search' : q} - dr.news</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"></meta>
      </Head>

        {q==='' 
            ?
                <QForm q={q} setQ={setQ}/>
            :
                <NewsSection API={API} setPage={setPage} page={page} q={q} setQ={setQ}/>
        }
                  
      
      <Footer selected={'search'}/>
    </>
  )
}
